### ISSUE TITLE
El Robert no sabe ir hacia adelante.

### ISSUE THREAD

**Issue by nicoosk** [nicoosk/robot-indep-robert#2]
**Actualmente el robot está solamente yendo hacia atrás, lo cual es un problema.** 

Debemos lograr que (de alguna manera), el Robert pueda acelerar de manera normal. Esto lo conseguimos con el puente H, siempre y cuándo conozcamos la lógica del circuito y qué pines están condicionados a las polaridades del motor.

**Comment by nicoosk-respaldo** [comment]
yoo
