### ISSUE TITLE
El servo motor necesita ayuda

### ISSUE THREAD

**Issue by nicoosk** [nicoosk/robot-indep-robert#5]
El servo motor se supone que está conectado, pero necesitamos que funcione como debe.

## ¿Qué necesitamos que haga?
Debemos lograr que el servo haga una rotación simple para que el sensor ultrasónico pueda verificar los objetos que tiene a su alrededor. 

- [x] Mirar al frente.
- [x] Mirar hacia la izquierda.
- [x] Mirar hacia la derecha.

**Comment by nicoosk-respaldo** [comment]
yoo

**Comment by nicoosk** [comment]
Aún estamos en proceso de verificar si el código funciona o no. Si resulta, este issue queda cerrado y concluido. Sino, se seguirá trabajando en esto.
